export interface User {
  id: any,
  firstName: string,
  lastName: string,
  address1: string,
  address2: string,
  town: string,
  county: string,
  postcode: string,
  email: string,
  telephone: string,
  analysis1: string,
  analysis2: string,
  analysis3: string,
  startDate: Date,
  country: string,
  hourlyRate: number,
  jobTitle: string,
  profileImage: string,
  emailVerified: boolean,
  organisationApproved: boolean,
  tenant: string,
  roles: string[]
}
